apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ecommerce-platform.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.application.service.type }}
  ports:
  - port: {{ .Values.application.service.port }}
    targetPort: {{ .Values.application.service.targetPort }}
    protocol: TCP
    name: http
    {{- if and (eq .Values.application.service.type "NodePort") .Values.application.service.nodePort }}
    nodePort: {{ .Values.application.service.nodePort }}
    {{- end }}
  selector:
    app: {{ .Values.application.name }}