apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "ecommerce_analytics"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  APP_ENV: "kubernetes"
  LOG_LEVEL: "INFO"