apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: dev
data:
  00-init.sql: |
    CREATE DATABASE IF NOT EXISTS ecommerce_analytics;
    USE ecommerce_analytics;
    GRANT ALL PRIVILEGES ON ecommerce_analytics.* TO 'ecommerce_user'@'%';
    GRANT ALL PRIVILEGES ON ecommerce_analytics.* TO 'root'@'%';
    FLUSH PRIVILEGES;