apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Root@123
  MYSQL_DATABASE: ecommerce_analytics
  MYSQL_USER: ecommerce_user
  MYSQL_PASSWORD: ecommerce_pass